version: '3'

services:
  backend-technical-test-app-container:
    image: backend-technical-test-app:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/backend-technical-test-app
    ports:
      - "8081:8081"