/* Copyright (c) 2022 Ali Saidi Elhassani
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 * 
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 * 
 */

package com.tui.proof.enums;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum Country {
	AD("Andorra"),
	AE("United Arab Emirates"),
	AF("Afghanistan"), 
	AG("Antigua & Barbuda"),
	AI("Anguilla"),
	AL("Albania"),
	AM("Armenia"),
	AO("Angola"),
	AQ("Antarctica"),
	AR("Argentina"), 
	AS("American Samoa"),
	AT("Austria"),
	AU("Australia"),
	AW("Aruba"),
	AX("Åland Islands"),
	AZ("Azerbaijan"), 
	BA("Bosnia & Herzegovina"),
	BB("Barbados"),
	BD("Bangladesh"),
	BE("Belgium"),
	BF("Burkina Faso"),
	BG("Bulgaria"),
	BH("Bahrain"),
	BI("Burundi"),
	BJ("Benin"),
	BL("St. Barthélemy"), 
	BM("Bermuda"), 
	BN("Brunei"),
	BO("Bolivia"),
	BQ("Caribbean Netherlands"),
	BR("Brazil"),
	BS("Bahamas"),
	BT("Bhutan"),
	BV("Bouvet Island"),
	BW("Botswana"),
	BY("Belarus"),
	BZ("Belize"),
	CA("Canada"), 
	CC("Cocos (Keeling) Islands"),
	CD("Congo - Kinshasa"),
	CF("Central African Republic"),
	CG("Congo - Brazzaville"),
	CH("Switzerland"),
	CI("Côte d’Ivoire"),
	CK("Cook Islands"),
	CL("Chile"),
	CM("Cameroon"),
	CN("China"),
	CO("Colombia"),
	CR("Costa Rica"),
	CU("Cuba"),
	CV("Cape Verde"),
	CW("Curaçao"),
	CX("Christmas Island"),
	CY("Cyprus"),
	CZ("Czechia"), 
	DE("Germany"),
	DJ("Djibouti"),
	DK("Denmark"),
	DM("Dominica"),
	DO("Dominican Republic"),
	DZ("Algeria"),
	EC("Ecuador"),
	EE("Estonia"),
	EG("Egypt"),
	EH("Western Sahara"),
	ER("Eritrea"),
	ES("Spain"), ET("Ethiopia"),
	FI("Finland"),
	FJ("Fiji"),
	FK("Falkland Islands"),
	FM("Micronesia"),
	FO("Faroe Islands"),
	FR("France"),
	GA("Gabon"),
	GB("United Kingdom"),
	GD("Grenada"),
	GE("Georgia"),
	GF("French Guiana"),
	GG("Guernsey"),
	GH("Ghana"),
	GI("Gibraltar"),
	GL("Greenland"),
	GM("Gambia"),
	GN("Guinea"),
	GP("Guadeloupe"),
	GQ("Equatorial Guinea"),
	GR("Greece"),
	GS("South Georgia & South Sandwich Islands"),
	GT("Guatemala"),
	GU("Guam"),
	GW("Guinea-Bissau"),
	GY("Guyana"),
	HK("Hong Kong SAR China"),
	HM("Heard & McDonald Islands"),
	HN("Honduras"),
	HR("Croatia"),
	HT("Haiti"),
	HU("Hungary"),
	ID("Indonesia"),
	IE("Ireland"),
	IL("Israel"),
	IM("Isle of Man"),
	IN("India"),
	IO("British Indian Ocean Territory"),
	IQ("Iraq"),
	IR("Iran"),
	IS("Iceland"), IT("Italy"),
	JE("Jersey"),
	JM("Jamaica"),
	JO("Jordan"),
	JP("Japan"),
	KE("Kenya"),
	KG("Kyrgyzstan"),
	KH("Cambodia"),
	KI("Kiribati"),
	KM("Comoros"),
	KN("St. Kitts & Nevis"),
	KP("North Korea"),
	KR("South Korea"),
	KW("Kuwait"),
	KY("Cayman Islands"),
	KZ("Kazakhstan"),
	LA("Laos"),
	LB("Lebanon"),
	LC("St. Lucia"),
	LI("Liechtenstein"),
	LK("Sri Lanka"),
	LR("Liberia"),
	LS("Lesotho"),
	LT("Lithuania"),
	LU("Luxembourg"),
	LV("Latvia"),
	LY("Libya"),
	MA("Morocco"),
	MC("Monaco"),
	MD("Moldova"),
	ME("Montenegro"),
	MF("St. Martin"),
	MG("Madagascar"),
	MH("Marshall Islands"),
	MK("Macedonia"),
	ML("Mali"),
	MM("Myanmar (Burma)"),
	MN("Mongolia"),
	MO("Macau SAR China"),
	MP("Northern Mariana Islands"),
	MQ("Martinique"),
	MR("Mauritania"),
	MS("Montserrat"),
	MT("Malta"),
	MU("Mauritius"),
	MV("Maldives"),
	MW("Malawi"),
	MX("Mexico"),
	MY("Malaysia"),
	MZ("Mozambique"),
	NA("Namibia"),
	NC("New Caledonia"),
	NE("Niger"),
	NF("Norfolk Island"),
	NG("Nigeria"),
	NI("Nicaragua"),
	NL("Netherlands"),
	NO("Norway"),
	NP("Nepal"),
	NR("Nauru"),
	NU("Niue"),
	NZ("New Zealand"),
	OM("Oman"),
	PA("Panama"),
	PE("Peru"),
	PF("French Polynesia"),
	PG("Papua New Guinea"),
	PH("Philippines"),
	PK("Pakistan"),
	PL("Poland"),
	PM("St. Pierre & Miquelon"),
	PN("Pitcairn Islands"),
	PR("Puerto Rico"),
	PS("Palestinian Territories"),
	PT("Portugal"),
	PW("Palau"),
	PY("Paraguay"),
	QA("Qatar"),
	RE("Réunion"),
	RO("Romania"),
	RS("Serbia"),
	RU("Russia"),
	RW("Rwanda"),
	SA("Saudi Arabia"),
	SB("Solomon Islands"),
	SC("Seychelles"),
	SD("Sudan"),
	SE("Sweden"),
	SG("Singapore"),
	SH("St. Helena"),
	SI("Slovenia"),
	SJ("Svalbard & Jan Mayen"),
	SK("Slovakia"),
	SL("Sierra Leone"),
	SM("San Marino"),
	SN("Senegal"),
	SO("Somalia"),
	SR("Suriname"),
	SS("South Sudan"),
	ST("São Tomé & Príncipe"),
	SV("El Salvador"),
	SX("Sint Maarten"),
	SY("Syria"),
	SZ("Swaziland"),
	TC("Turks & Caicos Islands"),
	TD("Chad"),
	TF("French Southern Territories"),
	TG("Togo"),
	TH("Thailand"),
	TJ("Tajikistan"),
	TK("Tokelau"),
	TL("Timor-Leste"),
	TM("Turkmenistan"),
	TN("Tunisia"),
	TO("Tonga"),
	TR("Turkey"),
	TT("Trinidad & Tobago"),
	TV("Tuvalu"),
	TW("Taiwan"),
	TZ("Tanzania"),
	UA("Ukraine"),
	UG("Uganda"),
	UM("U.S. Outlying Islands"),
	US("United States"),
	UY("Uruguay"),
	UZ("Uzbekistan"),
	VA("Vatican City"),
	VC("St. Vincent & Grenadines"),
	VE("Venezuela"),
	VG("British Virgin Islands"),
	VI("U.S. Virgin Islands"),
	VN("Vietnam"),
	VU("Vanuatu"),
	WF("Wallis & Futuna"),
	WS("Samoa"),
	YE("Yemen"),
	YT("Mayotte"),
	ZA("South Africa"),
	ZM("Zambia"),
	ZW("Zimbabwe");
	
	final String value;
	
	private Country(String value) {
		this.value = value;
    }

	@JsonValue
	public String getValue() {
		return this.value;
	}

	@JsonCreator
	public static Country fromValue(String value) {
		for (Country country : Country.values()) {
			if (country.value.equals(value) || country.name().equals(value)) {
				return country;
			}
		}
		return null;
	}
}
